# Generated by Django 4.2.2 on 2023-06-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="users.hotel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="typeOfRoom",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.typeofroom",
            ),
            preserve_default=False,
        ),
    ]
